spring:
  application:
    name: HostelHub Backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

server:
  port: 8080

app:
  version: 0.0.1-B0
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.hostelhub: DEBUG
